### ISSUE TITLE
Publish to pypi automatically

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#163]
Je pense la mise à jour du paquet sur [pypi](https://pypi.python.org/pypi/patacrep/4.0.0) est faite manuellement (@Luthaf tu confirmes ?)

Il est possible de le faire automatiquement (via [Travis](http://docs.travis-ci.com/user/deployment/pypi/) par exemple).

Le plus courant est de faire la mise à jour lorsqu'un nouveau tag apparaît sur master.

**Comment by Luthaf** [comment]
> Je pense la mise à jour du paquet sur pypi est faite manuellement (@Luthaf tu confirmes ?)

Je confirme !

**Comment by oliverpool** [comment]
@Luthaf c'est compliqué de mettre la release 5.0.0 sur pypi ?

**Comment by Luthaf** [comment]
Mieux que ça, je peut te passer les droits pour le faire =) Mais c'est (presque) aussi simple que `pip login` `pip publish` !

**Comment by oliverpool** [comment]
Encore mieux: https://docs.travis-ci.com/user/deployment/pypi

**Comment by Luthaf** [comment]
Voici mon mot de passe, encrypté:

```yaml
deploy:
  password:
    secure: NVTS+wQ55gy0w3ENlcJWBz6oKlI6k5+TwNinEl5EjxJXdxYU/rjH6D4Bm47q41hsd3IIPhTzexqCMB+sbuyQR8lIVLVVlFGQlqVw2hY8TZduFTPslnxgsna4zTG9aDwf1dJCI1ouRn6EybbAR0+DikXXTTnbB77n2/r8bJrKd2o=
```
