### ISSUE TITLE
Remplacer json par yaml

### ISSUE THREAD

**Issue by paternal** [patacrep/patacrep#182]
Dans : 
- le fichier .sb
- le [`include`](https://github.com/patacrep/patacrep/blob/72e3c202b976be47026d8016f48b27ebc3c69166/patacrep/content/include.py)
- les [templates](https://github.com/patacrep/patacrep/blob/master/patacrep/data/templates/songs.tex#L22-L65).

Pour tout ça, le mieux est d'attendre #111.

Début de la discussion : https://github.com/patacrep/patacrep/pull/179#issuecomment-158706487

**Comment by oliverpool** [comment]
Ca donnerait quelque chose comme cela (sachant qu'une `LISTE` serait en faite une suite d'éléments précédés par des `- `)

```yaml
book: 
  # L'idée est qu'on puisse définir un carnet fonctionnel juste avec cette section
  # (c'est la raison pour laquelle template est ici et non pas dans la section latex).
  template: STRING
  lang: STRING
  datadir: LISTE
  encoding: STRING
  pictures: BOOLEAN

content:
  # je propose d'en faire une section séparée
  # Cf #179

chords: # Options relatives aux accords
  diagramreminder : ENUM[important, none, all] (anciennement importantdiagramonly)
  diagrampage : BOOLEAN Montrer la page d'accords
  repeatchords: BOOLEAN
  lilypond: BOOLEAN
  instruments: LISTE[guitar, ukulele]
  show: BOOLEAN (anciennement booktype=chorded ou booktype=lyrics)
  notation: ENUM[alphascale, solfedge]

authors : # Comment sont analysés les auteurs
  separators: LISTE
  ignore: LISTE
  by: LISTE

titles : # Comment sont analysés les titres
  prefix: LISTE

latex : # Des choses spécifiques au LaTeX
  classoptions: STRING

color : # Des couleurs
  songnumber: STRING
  notebg: STRING
  indexbg: STRING

titlepage : #Configuration de la page de garde
  title: STRING
  author: STRING
  subtitle: STRING
  version: STRING
  url: STRING
  email: STRING
  picture: STRING
  picturecopyright: STRING
  footer: STRING
```
