### ISSUE TITLE
Idées de song_plugins

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep#206]
Pour écrire quelques idées de plugin que j'ai en tête (mais sans aucune urgence quant à l'implémentation):

- Filtrer les chants par langue: #196 
- Forcer un saut dans la numérotation des chants , par exemple pour que les chansons d'amours soient comptées à partir du numéro 101
```yaml
song_counter: 101
```
- Système de "pagination", pour la génération de différents volumes par exemple
```yaml
select_songs:
  limit: 50     # au maximum 50 chants (chordpro ou latex)
  offset: 10  # à partir du 10ème
  content: ...
```
