### ISSUE TITLE
Les prefixs dans la gestion des titres pour l'index ne fonctionnent pas/plus

### ISSUE THREAD

**Issue by takuyozora** [patacrep/patacrep#280]
Bonjour,

J'ai pas mal bidouillé patacrep dans mon coins (et fais quelques PR quand même) et je pensais que le fait que l'index ne gérait plus les prefix venait de ça, mais j'ai récemment voulu vérifier et en partant d'un `venv` tout propre et en téléchargeant la dernière version en date (5.2.0) avec un simple fichier de test cela semble ne pas fonctionner non plus.

Le fichier YAML en question : 
```yaml
content:
  - "georges_brassens/la_mauvaise_reputation.sg"
  - "georges_brassens/chanson_pour_l_auvergnat.sg"
  - "kyo/derniere_danse.sg"
  - "the_doors/*"
  - "michel_sardou/*"
  - "adele/*"
  - "aaron/*"
  - "alain_bashung/*"
  - "aldebert/*"
  - "alain_souchon/*"
  - "alexis_hk/*"
  - "amplitude/*"
  - "america/*"
  - "amy_macdonald/*"
  - "anais/*"
  - "anis/*"
  - "antoine/*"
  - "as_de_trefle/*"
  - "avril_lavigne/*"
  - "benabar/*"
  - "bernard_lavilliers/*"
  - "bob_dylan/*"
  - "gospel/*"
  - "gregoire/*"
  - "henri_des/*"
  - "m/*"
  - "scouts/*"

book:
  lang: en
  encoding: utf-8
  pictures: yes
  template: patacrep.tex
  onesongperpage: no
  datadir: "patadata"

chords: # Options relatives aux accords
  show: yes
  diagramreminder: important
  repeatchords: yes
  lilypond: no
  tablatures: no
  instrument: guitar
  notation: alphascale

authors: # Comment sont analysés les auteurs
  separators:
  - and
  ignore:
  - unknown
  after:
  - by

titles: # Comment sont analysés les titres
  prefix:
  - The
  - Le
  - La
  - "L'"
  - A
  - Au
  - Ces
  - De
  - Des
  - El
  - Les
  - Ma
  - Mon
  - Un
```

Inspiré de la documentation : https://patacrep.readthedocs.io/fr/latest/book/introduction.html et j'ai mis beaucoup de chants (issus de patadat) pour provoquer l'affichage en section par première lettre.

La compilation (depuis le venv) : `./venv/bin/songbook test.yaml -v`
Aucune erreur n’apparaît. 

Résultat attendu : Les chants dont la/les premières lettres de leur titre sont listées dans `prefix` (Le, La, ...etc) apparaissent dans la section de la première lettre de leur titre hors préfix.

Résultat obtenu : Les chants apparaissent tous dans leur section en fonction de la première lettre de leur titre, sans prendre en compte la liste des `prefix`

Voir le fichier PDF compilé : [test.pdf](https://github.com/patacrep/patacrep/files/10900847/test.pdf)

Par exemple : 
 - La mauvaise réputation devrait apparaître dans la section [**M**] à **Mauvaise réputation, La** et non pas dans la section [**L**] à **La Mauvaise réputation**

Suis-je le seul à avoir ce comportement ? Est-ce que c'est bien un bug ou n'ai-je tout simplement pas compris le fonctionnement de cette option ? Avez-vous des pistes sur comment obtenir le comportement souhaité ?

Merci d'avance et heureux d'apprendre que de nouvelles personnes participent à patacrep.
